### ISSUE TITLE
UM2_Sequencer_tube_modified_tighter_Higher_Motor.stl - seems to be wrong ....

### ISSUE THREAD

**Issue by Daffy2905** [HEN3DRIK/BeadSorter#2]
Hi Hendrik! 

It seems the noted file UM2_Sequencer_tube_modified_tighter_Higher_Motor.stl is not correct. I think the led and the photorisitor should have a connection, but in the file there is wall between them. Also the perlerbeads cannot fall down in the analyser because there is also a block. 

THANK you for the great project ....
David

**Comment by HEN3DRIK** [comment]
Thank you, sorry that it took so long. Fixed it.
