### ISSUE TITLE
Danke für die hilfe mit dem Servo. Dieser Vorgang funktioniert einwandfrei. Leider hat sich ein anders Problem aufgetan Wenn ich die Maschine starte bewegt sich der stepper motor nicht und auch der farb scan auch nicht der servo bewegt sich 4 mal dannach stellt er seinen arbeit wieder ein nur mehr der  Hopper motor dreht das wars. Ich bin mir nicht ganz sicher ob der Stepper richtig am Driver verbunden ist .Und wieso die  maschine nicht automatisch zum sortieren anfang. vielen dank für ihre hilfe und ein Schönes Wochende noch mit freundlichen grüße Fabian

### ISSUE THREAD

**Issue by Fapi097** [HEN3DRIK/BeadSorter#4]
Danke für die hilfe mit dem Servo. Dieser Vorgang funktioniert einwandfrei. Leider hat sich ein anders Problem aufgetan Wenn ich die Maschine starte bewegt sich der stepper motor nicht und auch der farb scan auch nicht der servo bewegt sich 4 mal dannach stellt er seinen arbeit wieder ein nur mehr der  Hopper motor dreht das wars. Ich bin mir nicht ganz sicher ob der Stepper richtig am Driver verbunden ist .Und wieso die  maschine nicht automatisch zum sortieren anfang. vielen dank für ihre hilfe und ein Schönes Wochende noch mit freundlichen grüße Fabian

_Originally posted by @Fapi097 in https://github.com/HEN3DRIK/BeadSorter/issues/3#issuecomment-1454113488_

**Comment by HEN3DRIK** [comment]
I closed this: Copy of https://github.com/HEN3DRIK/BeadSorter/issues/3#issuecomment-1454113488
